### ISSUE TITLE
ActionView::MissingTemplate (Missing template sessions/new + Completed 500 Internal Server Error

### ISSUE THREAD

**Issue by kirantpatil** [kirantpatil/park-mgmt#1]
Started GET "/floor_stream" for 127.0.0.1 at 2015-07-16 10:20:08 +0530
Processing by FloorsController#floor_stream as text/event-stream
Redirected to http://localhost:3000/session/new
Filter chain halted as :require_signin rendered or redirected
Completed 302 Found in 3ms (ActiveRecord: 0.0ms)

Started GET "/session/new" for 127.0.0.1 at 2015-07-16 10:20:08 +0530
Processing by SessionsController#new as text/event-stream
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)

ActionView::MissingTemplate (Missing template sessions/new, application/new with {:locale=>[:en], :formats=>["text/event-stream"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
- "/home/kpatil/work/nagaraj/svg_nload/app/views"
  ):
  actionview (4.2.1) lib/action_view/path_set.rb:46:in `find'
  actionview (4.2.1) lib/action_view/lookup_context.rb:121:in`find'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:40:in`determine_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:8:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in`render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in`_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in`render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in`render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in`render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in`block in ms'
  /home/kpatil/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in`ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in`cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in`render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:5:in`send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in`call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in`block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in`call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in`_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in`process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in`block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in`process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in`call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in`serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in`each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in`call'
  rack (1.6.1) lib/rack/etag.rb:24:in `call'
  rack (1.6.1) lib/rack/conditionalget.rb:25:in`call'
  rack (1.6.1) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.1) lib/rack/session/abstract/id.rb:225:in`context'
  rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in`call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in`call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in`_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in`call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in`block in tagged'

**Comment by kirantpatil** [comment]
Moved sse logic to static controller where we don't have require_login: stuff and it worked fine.
code commit :  https://github.com/kirantpatil/park-mgmt/commit/229798b101ef039d0649f75ea7e66fc08ef114e3
